// import React from 'react'
// import Head from 'next/head'
// import Navbar from "./navbar"
// const About = () => {
//   return (
//     <div>
//          <Head>
// //         <title>About</title>
// //         <meta name="description" content="Generated by Roshnn" />
// //         <link rel="icon" href="/favicon.ico" />
// //       </Head>
//         <h2>About</h2>
//     </div>
//   )
// }

// export default About
