import Head from 'next/head'
import Header from '../components/header'
import MainContent from '../components/MainBody'
const Home = () => {

  return (

    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by Roshnn" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <MainContent />

        {/* sidebar */}
        {/* feed */}
        {/* widgets */}
      </main>

    </div>
  )
}

export default Home
