// import React from 'react'
// import Head from 'next/head'
// import Navbar from "./navbar"
// const Product = () => {
//   return (
//     <div>
//       <Head>
//         <title>Product</title>
//         <meta name="description" content="Generated by Roshnn" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <h2>Product</h2>
//     </div>
//   )
// }

// export default Product
